import type { Extension } from "@codemirror/state";
import { liveMdCodeFenceHighlighting } from "@codemirror-treesitter/live-md";
import {
  createCodeMirrorTheme,
  createEditorTheme,
  createHighlightStyle,
  type SemanticThemeSpec,
} from "@codemirror-treesitter/theme";

export const githubLightColors = {
  accent: "#0969da",
  accentMuted: "#0969da1f",
  attention: "#9a6700",
  attentionMuted: "#fff8c5",
  background: "#ffffff",
  border: "#d0d7de",
  borderMuted: "#d8dee4",
  comment: "#6e7781",
  cursor: "#0969da",
  danger: "#cf222e",
  dangerMuted: "#cf222e26",
  entity: "#8250df",
  foreground: "#24292f",
  foregroundMuted: "#6e7781",
  foregroundSubtle: "#57606a",
  inserted: "#116329",
  number: "#0550ae",
  property: "#953800",
  searchSelected: "#ffd33d66",
  selection: "#0969da26",
  string: "#0a3069",
  subtleBackground: "#f6f8fa",
} as const;

export const githubLightThemeSpec: SemanticThemeSpec = {
  appearance: "light",
  chrome: {
    activeLine: githubLightColors.subtleBackground,
    background: githubLightColors.background,
    border: githubLightColors.border,
    cursor: githubLightColors.cursor,
    foldPlaceholderBorder: githubLightColors.border,
    foldPlaceholderText: githubLightColors.foregroundMuted,
    foreground: githubLightColors.foreground,
    gutterActiveBackground: githubLightColors.subtleBackground,
    gutterActiveForeground: githubLightColors.foregroundSubtle,
    gutterBackground: githubLightColors.background,
    gutterBorder: githubLightColors.borderMuted,
    gutterForeground: githubLightColors.foregroundMuted,
    matchingBracketBackground: githubLightColors.accentMuted,
    matchingBracketBorder: githubLightColors.accent,
    nonmatchingBracketBackground: githubLightColors.dangerMuted,
    nonmatchingBracketBorder: githubLightColors.danger,
    panelBackground: githubLightColors.subtleBackground,
    panelBorder: githubLightColors.border,
    panelForeground: githubLightColors.foreground,
    searchMatch: githubLightColors.attentionMuted,
    searchMatchBorder: githubLightColors.attention,
    searchMatchSelected: githubLightColors.searchSelected,
    selection: githubLightColors.selection,
    selectionMatch: githubLightColors.accentMuted,
    tooltipBackground: githubLightColors.background,
    tooltipBorder: githubLightColors.border,
    tooltipForeground: githubLightColors.foreground,
    tooltipSelectedBackground: githubLightColors.subtleBackground,
    tooltipSelectedForeground: githubLightColors.foreground,
  },
  syntax: {
    atom: githubLightColors.number,
    bool: githubLightColors.number,
    character: githubLightColors.inserted,
    className: githubLightColors.property,
    comment: githubLightColors.comment,
    constant: githubLightColors.number,
    definition: githubLightColors.foreground,
    deleted: githubLightColors.danger,
    escape: githubLightColors.inserted,
    functionName: githubLightColors.entity,
    heading: githubLightColors.foreground,
    inserted: githubLightColors.inserted,
    invalid: githubLightColors.danger,
    keyword: githubLightColors.danger,
    labelName: githubLightColors.entity,
    link: githubLightColors.accent,
    macroName: githubLightColors.entity,
    meta: githubLightColors.comment,
    modifier: githubLightColors.danger,
    namespace: githubLightColors.foreground,
    number: githubLightColors.number,
    operator: githubLightColors.foreground,
    propertyName: githubLightColors.property,
    regexp: githubLightColors.inserted,
    separator: githubLightColors.foreground,
    specialString: githubLightColors.inserted,
    specialVariable: githubLightColors.number,
    standardName: githubLightColors.foreground,
    string: githubLightColors.string,
    typeName: githubLightColors.property,
    url: githubLightColors.accent,
    variableName: githubLightColors.foreground,
  },
};

export const githubLightTheme = createEditorTheme(githubLightThemeSpec);
export const githubLightHighlightStyle = createHighlightStyle(githubLightThemeSpec.syntax);
export const githubLight: Extension = createCodeMirrorTheme(githubLightThemeSpec);
export const githubLightLiveMdExtensions: Extension = [
  githubLight,
  liveMdCodeFenceHighlighting(githubLightHighlightStyle),
];
