import {
  createLiveMdTheme,
  type LiveMdThemeColorVariables,
} from "@codemirror-treesitter/live-md-theme";
import { githubLightColors as c } from "@codemirror-treesitter/theme-palettes";

const githubLightLiveMdVariables: LiveMdThemeColorVariables = {
  "--live-md-active-line": "#0969da0f",
  "--live-md-accent": c.accent,
  "--live-md-accent-2": c.accent,
  "--live-md-bg": c.background,
  "--live-md-blockquote": c.foregroundSubtle,
  "--live-md-blockquote-border": c.border,
  "--live-md-border": c.border,
  "--live-md-code-bg": c.subtleBackground,
  "--live-md-code-border": c.border,
  "--live-md-code-muted": c.foregroundSubtle,
  "--live-md-code-text": c.foreground,
  "--live-md-cursor": c.cursor,
  "--live-md-error": c.danger,
  "--live-md-error-border": c.danger,
  "--live-md-heading-1": c.foreground,
  "--live-md-heading-2": c.foreground,
  "--live-md-heading-3": c.foreground,
  "--live-md-heading-rest": c.foreground,
  "--live-md-inline-code-bg": "#afb8c133",
  "--live-md-inline-code-border": c.border,
  "--live-md-inline-code-text": c.foreground,
  "--live-md-latex": c.foreground,
  "--live-md-link": c.accent,
  "--live-md-link-underline": "#0969da66",
  "--live-md-list-marker": c.foregroundSubtle,
  "--live-md-mermaid-accent": c.accent,
  "--live-md-mermaid-bg": c.background,
  "--live-md-mermaid-border": c.border,
  "--live-md-mermaid-line": c.foregroundSubtle,
  "--live-md-mermaid-muted": c.foregroundSubtle,
  "--live-md-mermaid-surface": c.background,
  "--live-md-mermaid-text": c.foreground,
  "--live-md-muted": c.foregroundSubtle,
  "--live-md-ordered-marker": c.foregroundSubtle,
  "--live-md-rule": c.border,
  "--live-md-selection": "#0969da22",
  "--live-md-surface": c.subtleBackground,
  "--live-md-surface-error": "#ffebe9",
  "--live-md-surface-error-border": c.danger,
  "--live-md-syntax": c.foregroundMuted,
  "--live-md-table-bg": c.background,
  "--live-md-table-border": c.border,
  "--live-md-table-divider": "#8c959f",
  "--live-md-table-header-bg": c.subtleBackground,
  "--live-md-table-header-text": c.foreground,
  "--live-md-table-line-bg": c.subtleBackground,
  "--live-md-table-pipe": "#afb8c1",
  "--live-md-task-bg": c.background,
  "--live-md-task-border": "#8c959f",
  "--live-md-task-check": c.background,
  "--live-md-task-checked": c.foregroundMuted,
  "--live-md-task-checked-strong": c.foregroundSubtle,
  "--live-md-text": c.foreground,
};

export const githubLightLiveMdTheme = createLiveMdTheme({
  appearance: "light",
  id: "github-light",
  variables: githubLightLiveMdVariables,
});
