import type { Extension } from "@codemirror/state";
import { EditorView } from "@codemirror/view";
declare const HTMLElementBase: typeof HTMLElement;
export declare class LiveMdEditorElement extends HTMLElementBase {
    static observedAttributes: string[];
    private controller;
    private cleanValue;
    private dirtySinceChange;
    private editorExtensions;
    private explicitValue;
    private mount;
    private shadow;
    private storedDefaultValue;
    private storedSelectionEnd;
    private storedSelectionStart;
    private storedValue;
    ready: Promise<void>;
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    attributeChangedCallback(name: string, oldValue: string | null, newValue: string | null): void;
    get defaultValue(): string;
    set defaultValue(value: string);
    get persistKey(): null | string;
    set persistKey(value: null | string);
    get placeholder(): string;
    set placeholder(value: string);
    get readOnly(): boolean;
    set readOnly(value: boolean);
    get value(): string;
    set value(value: string);
    get view(): EditorView | null;
    get extensions(): Extension;
    set extensions(value: Extension | null | undefined);
    get dirty(): boolean;
    get selectionStart(): number;
    set selectionStart(value: number);
    get selectionEnd(): number;
    set selectionEnd(value: number);
    focus(): void;
    blur(): void;
    markClean(): void;
    setSelectionRange(start: number, end: number): void;
    select(): void;
    private handleEditorInput;
    private dispatchPendingChange;
    private dispatchLiveMdError;
    private handleEditorSelection;
    private applyStoredSelection;
    private clampStoredSelection;
    private currentSelection;
    private currentExtensions;
    private storeCurrentSelection;
    private updateStoredSelection;
}
export declare function defineLiveMdEditor(tagName?: string): void;
export {};
